import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { io as connect, type Socket } from "socket.io-client";
import { cleanupRooms, httpServer, rooms, stopRooms, tickRoom } from "./index.js";

let url:string;const clients:Socket[]=[];
const client=()=>{const s=connect(url,{forceNew:true,transports:["websocket"]});clients.push(s);return s};
const emitAck=<T>(s:Socket,event:string,data?:unknown)=>new Promise<T>(resolve=>data===undefined?s.emit(event,resolve):s.emit(event,data,resolve));

beforeAll(async()=>{await new Promise<void>(resolve=>httpServer.listen(0,"127.0.0.1",resolve));const a=httpServer.address();if(!a||typeof a==="string")throw new Error("No test port");url=`http://127.0.0.1:${a.port}`});
afterAll(async()=>{clients.forEach(s=>s.disconnect());rooms.forEach(r=>{if(r.timer)clearInterval(r.timer)});rooms.clear();await new Promise<void>(resolve=>httpServer.close(()=>resolve()))});

describe("Socket.IO room lifecycle",()=>{
 it("acknowledges valid latency probes",async()=>{const socket=client(),sentAt=Date.now();const response=await emitAck<{sentAt:number;serverAt:number}>(socket,"connection:ping",{sentAt});expect(response.sentAt).toBe(sentAt);expect(response.serverAt).toBeGreaterThanOrEqual(sentAt)});
 it("reports readiness and stops every active room timer",async()=>{const response=await fetch(`${url}/ready`);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({ready:true});const display=client();const created=await emitAck<{roomCode:string}>(display,"room:create");const room=rooms.get(created.roomCode)!;room.timer=setInterval(()=>{},1000);stopRooms();expect(room.timer).toBeUndefined()});
 it("expires only empty rooms older than the cleanup TTL",async()=>{const display=client();const created=await emitAck<{roomCode:string}>(display,"room:create");const room=rooms.get(created.roomCode)!;display.disconnect();await new Promise(r=>setTimeout(r,20));const emptySince=room.emptySince!;room.timer=setInterval(()=>{},1000);cleanupRooms(emptySince+119999);expect(rooms.has(created.roomCode)).toBe(true);cleanupRooms(emptySince+120001);expect(rooms.has(created.roomCode)).toBe(false);expect(room.timer).toBeUndefined()});
 it("ticks countdown into play and resolves both round outcomes",async()=>{const display=client();const created=await emitAck<{roomCode:string}>(display,"room:create");const room=rooms.get(created.roomCode)!;room.state.phase="countdown";room.state.countdown=1;tickRoom(room,1000);expect(room.state.phase).toBe("playing");expect(room.state.target).not.toBeNull();room.state.timeLeft=1;room.state.health=3;tickRoom(room,2000);expect(room.state).toMatchObject({phase:"finished",outcome:"victory",message:"Rift sealed"});room.state.phase="playing";room.state.outcome=null;room.state.timeLeft=90;room.state.health=1;room.state.target={id:"last",kind:"red",x:.5,y:.5,radius:.1,expiresAt:2999,hits:[],hitAt:{}};room.timer=setInterval(()=>{},1000);tickRoom(room,3000);expect(room.state).toMatchObject({phase:"finished",outcome:"defeat",health:0,message:"Containment failed"});expect(room.timer).toBeUndefined()});
 it("creates a room, assigns two players, rejects a third, and reconnects display",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");expect(created.roomCode).toHaveLength(6);const p1=await emitAck<{ok:boolean;playerId:number;token:string}>(client(),"room:join",{roomCode:created.roomCode,role:"player"});const p2=await emitAck<{ok:boolean;playerId:number}>(client(),"room:join",{roomCode:created.roomCode,role:"player"});expect([p1.playerId,p2.playerId]).toEqual([1,2]);const full=await emitAck<{ok:boolean;error:string}>(client(),"room:join",{roomCode:created.roomCode,role:"player"});expect(full).toMatchObject({ok:false,error:"Room sudah penuh"});const resumed=await emitAck<{ok:boolean}>(client(),"room:join",{roomCode:created.roomCode,role:"display",token:created.token});expect(resumed.ok).toBe(true)});
 it("closes a room only with the display token",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");display.emit("room:close",{roomCode:created.roomCode,token:"wrong"});await new Promise(r=>setTimeout(r,20));expect(rooms.has(created.roomCode)).toBe(true);display.emit("room:close",{roomCode:created.roomCode,token:created.token});await new Promise(r=>setTimeout(r,20));expect(rooms.has(created.roomCode)).toBe(false)});
 it("allows only the display to clamp tutorial steps",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");display.emit("tutorial:set",{roomCode:created.roomCode,token:"wrong",step:3});await new Promise(r=>setTimeout(r,20));expect(rooms.get(created.roomCode)?.state.tutorialStep).toBe(0);display.emit("tutorial:set",{roomCode:created.roomCode,token:created.token,step:99});await new Promise(r=>setTimeout(r,20));expect(rooms.get(created.roomCode)?.state.tutorialStep).toBe(4)});
 it("consumes ammo and allows an authenticated reload",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");const player=client();const joined=await emitAck<{playerId:1;token:string}>(player,"room:join",{roomCode:created.roomCode,role:"player"});const room=rooms.get(created.roomCode)!;room.state.phase="playing";player.emit("controller:shoot",{roomCode:created.roomCode,playerId:joined.playerId,token:joined.token,sequence:1,clientTime:Date.now()});await new Promise(r=>setTimeout(r,20));expect(room.state.ammo[1]).toBe(5);player.emit("controller:reload",{roomCode:created.roomCode,playerId:joined.playerId,token:"wrong"});await new Promise(r=>setTimeout(r,20));expect(room.state.ammo[1]).toBe(5);player.emit("controller:reload",{roomCode:created.roomCode,playerId:joined.playerId,token:joined.token});await new Promise(r=>setTimeout(r,20));expect(room.state.ammo[1]).toBe(room.state.maxAmmo)});
 it("pauses when a player disconnects and permits resume after token reclaim",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");const p1=client(),p2=client();const one=await emitAck<{playerId:1;token:string}>(p1,"room:join",{roomCode:created.roomCode,role:"player"});await emitAck(p2,"room:join",{roomCode:created.roomCode,role:"player"});const room=rooms.get(created.roomCode)!;room.state.phase="playing";room.state.target={id:"pause",kind:"red",x:.5,y:.5,radius:.1,expiresAt:Date.now()+1000,hits:[],hitAt:{}};p1.disconnect();await new Promise(r=>setTimeout(r,20));expect(room.state).toMatchObject({phase:"paused",players:{1:false,2:true},message:"Player 1 link lost"});const oldExpiry=room.state.target!.expiresAt;const replacement=client();const reclaimed=await emitAck<{state:{phase:string;message?:string}}>(replacement,"room:join",{roomCode:created.roomCode,role:"player",token:one.token});expect(reclaimed.state.phase).toBe("playing");expect(reclaimed.state.message).toBeUndefined();expect(room.state.phase).toBe("playing");expect(room.state.target!.expiresAt).toBeGreaterThanOrEqual(oldExpiry)});
 it("runs authenticated hand mode through authoritative aim, shoot, and reload",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");const room=rooms.get(created.roomCode)!;display.emit("control:set",{roomCode:created.roomCode,token:"wrong",mode:"hand"});await new Promise(r=>setTimeout(r,20));expect(room.state.controlMode).toBe("phone");display.emit("control:set",{roomCode:created.roomCode,token:created.token,mode:"hand"});await new Promise(r=>setTimeout(r,20));expect(room.state).toMatchObject({controlMode:"hand",players:{1:true,2:true}});room.state.phase="playing";room.state.target={id:"hand",kind:"red",x:.4,y:.5,radius:.1,expiresAt:Date.now()+1000,hits:[],hitAt:{}};display.emit("hand:aim",{roomCode:created.roomCode,token:created.token,playerId:1,x:.4,y:.5,sequence:1});await new Promise(r=>setTimeout(r,20));expect(room.state.aims[1]).toMatchObject({x:.4,y:.5,sequence:1});display.emit("hand:shoot",{roomCode:created.roomCode,token:created.token,playerId:1,sequence:2,clientTime:Date.now()});await new Promise(r=>setTimeout(r,20));expect(room.state.stats[1]).toMatchObject({shots:1,hits:1});expect(room.state.ammo[1]).toBe(5);display.emit("hand:reload",{roomCode:created.roomCode,token:created.token,playerId:1});await new Promise(r=>setTimeout(r,20));expect(room.state.ammo[1]).toBe(room.state.maxAmmo)});
 it("rejects hand events outside hand mode",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");const room=rooms.get(created.roomCode)!;const before=structuredClone(room.state);display.emit("hand:aim",{roomCode:created.roomCode,token:created.token,playerId:1,x:.8,y:.2,sequence:1});display.emit("hand:shoot",{roomCode:created.roomCode,token:created.token,playerId:1,sequence:2,clientTime:Date.now()});await new Promise(r=>setTimeout(r,20));expect(room.state).toEqual(before)});
 it("keeps display-initiated pauses manual",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");const p1=client(),p2=client();const one=await emitAck<{token:string}>(p1,"room:join",{roomCode:created.roomCode,role:"player"});await emitAck(p2,"room:join",{roomCode:created.roomCode,role:"player"});const room=rooms.get(created.roomCode)!;room.state.phase="playing";display.emit("game:pause",{roomCode:created.roomCode,token:created.token});await new Promise(r=>setTimeout(r,20));expect(room.state).toMatchObject({phase:"paused",message:"Paused by display"});p1.disconnect();await new Promise(r=>setTimeout(r,20));const replacement=client();await emitAck(replacement,"room:join",{roomCode:created.roomCode,role:"player",token:one.token});expect(room.state.phase).toBe("paused")});
 it("ignores malformed realtime payloads without mutating room state",async()=>{const display=client();const created=await emitAck<{roomCode:string;token:string}>(display,"room:create");const room=rooms.get(created.roomCode)!;const before=structuredClone(room.state);display.emit("game:start",null);display.emit("game:pause","bad");display.emit("tutorial:set",{roomCode:created.roomCode,token:created.token,step:NaN});display.emit("controller:aim",{roomCode:created.roomCode,token:created.token,playerId:99,x:NaN,y:Infinity,sequence:-1});display.emit("controller:shoot",{});display.emit("controller:reload",null);await new Promise(r=>setTimeout(r,20));expect(rooms.has(created.roomCode)).toBe(true);expect(room.state).toEqual(before)});
});
